/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_saif_window_supp_bv (void);
GtkWidget* create_saif_window_aff (void);
GtkWidget* create_saif_window_aj (void);
GtkWidget* create_saif_window_mod (void);
GtkWidget* create_saif_window_login (void);
GtkWidget* create_statistique (void);
